### ISSUE TITLE
Remove json.dumps() for improve readability and compatibility with attributes['data']

### ISSUE THREAD

**Issue by benjamfk** [youdroid/home-assistant-sickchill#13]
I noticed that the attributes are stored as a json string which isn't the same as the plex_recently_added. Instead I would recommend to store them as is by chaning: 

`attributes['data'] = json.dumps(card_json)`
to:
`attributes['data'] = card_json`

After the change:
![image](https://user-images.githubusercontent.com/64400812/94655811-705d2280-02ff-11eb-80ee-65794a54c6f9.png)

There are two advantages as far as I can tell...
1) Increased readability
2) Compatible with other cards such as flex-table-card which I use instead of the upcoming-media-card

**Comment by youdroid** [comment]
I'm just inspired by plex_recently_added integration, and the return of this integration is in the format of table json.

So I did the same thing, but yes I also tested my side and it also works in the simple format of string.

So I was only thinking of using upcoming-media-card, that's why I used the json. But if you tell me that other cards can use this integration then why not actually change the return format.

I'm curious to see the graphics rendering with flex-table-card, if it's possible to show me an example?
 
Maybe I'll add a parameter in the integration to format the sensor feedback.
This way I make sure that it is still compatible with upcoming-media-card, and for you you can change it to make it compatible with other cards.

What do you think about that ?

**Comment by benjamfk** [comment]
After removing the jsom.dumps the structure of this sensor is similar too what plex_recently_added uses.
Before it looked like this which doesn't play nicely with flex-table-card:
![image](https://user-images.githubusercontent.com/64400812/94785744-5fc8ad00-03d0-11eb-8513-6f1c1ea47c41.png)

Compared to the plex integration:
![image](https://user-images.githubusercontent.com/64400812/94785819-78d15e00-03d0-11eb-835d-c461a8627a7d.png)

My current layout with flex-table-card looks like this. I'm not a big fan of the looks of the "upcoming-media-card" and I already use the "flex-table-card" for a lot of other stuff because it's so flexible (it supports javascript for modifying data). The only thing I miss now is "missing episodes" that have aired, but for some reason haven't been added to Plex. My intention is to extend this component to also include missed episodes so I can have them on top of "Upcoming TV Shows" with a red background or so and a "search for"-button for quickly trying to search for it again (similar to the "Schedule" view in Medusa). :)
![image](https://user-images.githubusercontent.com/64400812/94786267-0614b280-03d1-11eb-94c0-63cd20397232.png)

**Comment by youdroid** [comment]
Ok, I'll add a parameter, to format the return as a string.
So you can use this integration with other cards.
I will add this param in the next release !

Thank you for your feedback, I didn't know that the "flex-table-card" card could do so many things and that we could couple it with this type of integration.
I admit that what you are showing me is interesting that I am going to test it at my HA!

If it can help you in your project, I have in mind to offer sickchill services that can be called from HA to force the search for episodes, or even refresh a show in SickChill for example.
Some services offered natively in sickchill, but called from this integration.

When I have some time I will develop it :wink:
